---
video_user: "ioanbsu"
influx_db_url: "http://localhost:8081"
influx_db_login: "INSERT_INFLUX_DB_LOGIN_HERE"
influx_db_pwd : "INSERT_INFLUX_DB_PWD_HERE"
influx_db_host_name_to_report: "surv"
video_record_home_dir: "/home/ioanbsu/surv"
cameras:
    - {ip: 192.168.1.101 , name: "cam1", port: 554, credentials: "username:password@" }
    - {ip: 192.168.1.102 , name: "cam2", port: 554, credentials: "" }
cameras_to_mjpeg:
    - {ip: 192.168.1.102 , name: "cam2", port: 554, credentials: "username1:password1@" }